service: serverless-rest-api-with-dynamodb


provider:
  name: aws
  stage: dev
  region: us-east-2
  runtime: nodejs16.x
  apiGateway:
    binaryMediaTypes:
      - '*/*' ##API Gateway passes the binary files as base64 encoded, so you’ll need to decode from base64 before passing the body to parse-multipart.
  environment:
    DYNAMODB_TABLE: test
    DYNAMODB_TABLE_USERTICKET: testUserticket
    DYNAMODB_TABLE_IMAGE: testUpload
    BUCKET: warsamestorages
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem

          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes
  - serverless-iam-roles-per-function

custom:
  profile:
    dev: default
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      port: 8000
      seed: true
      sharedDb: true
      migrate: true 
    seed:
      domain:
        sources:
          - table: test
            sources: [./test.json]
functions:
  createEvent:
    handler: todos/createEvent.create
    events:
      - http:
          path: todos/event
          method: post
          cors: true
  listEvents:
    handler: todos/listEvents.list
    events:
      - http:
          path: todos/event
          method: get
          cors: true
  getEvent:
    handler: todos/getEvent.get
    events:
      - http:
          path: todos/event/{id}
          method: get
          cors: true        
  buyTicket:
    handler: todos/buyTicket.buy
    events:
      - http:
          path: todos/userticket
          method: post
          cors: true
  listTickets:
    handler: todos/listTickets.list
    events:
      - http:
          path: todos/userticket
          method: get
          cors: true	
  upload:
    handler: todos/upload.upload
    events:
      - http:
          path: todos/upload
          method: put
          cors: true
    memorySize: 512 # optional, in MB, default is 1024
    timeout: 10 # 
    iamRoleStatements:
      - Effect: Allow
        Action:
         - "s3:Put*"
         - "s3:Get*" 
        Resource: arn:aws:s3:::warsamestorages/*
  uploadget:
    handler: todos/uploadget.upload
    events:
      - http:
          path: todos/upload
          method: get
          cors: true              

                             
resources:
  Resources:
    WarsameStorages:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: warsamestorages
        AccessControl: PublicRead
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: test
    TodosDynamoDbTableUserTicket:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: testUserticket
    TodosDynamoDbTableImage:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: testImage              